### ISSUE TITLE
Redundant GET methods

### ISSUE THREAD

**Issue by skyline220** [ilanasufrin/nyu-devops-homework-1#37]
Please list_all_ice_creams and get_popular_ice_cream have redundant method signatures which is causing an error in testing. Please combine these two methods so this error no longer exists. I believe Soumie worked on this so please fix this

**Comment by Cantal0p3** [comment]
I am not sure I understand the issue. list_all_ice_creams and get_popular_ice_cream are two different methods with different purposes, its not prudent to merge these. Secondly, I see during your commit -"Updated Querying by state and updating status method, also added unit…", you changed the app.route for get_popular_ice_cream(), that could have caused the error you are talking about. I have reverted the change with the fix I pushed for bug report #31. I tested with the latest code from git. List, Add, Delete, Update, Retrieve one icecream by id and get popular icecreams are working as expected.

**Comment by skyline220** [comment]
Soumie the professor himself said this was an issue. There should not be two get methods, they need to be combined. He said this code is incorrect and should have never been pushed in the first place. Please assign this back to yourself and speak to the professor directly if you feel I am not correct.

**Comment by Cantal0p3** [comment]
So what you are saying is get_popular_ice_cream() is not correct because there are multiple get methods. I still don't understand as the method is working as expected without any error. Ok I will speak to professor tomorrow before class.

**Comment by sschweber** [comment]
@Cantal0p3 since it's due tomorrow at 5pm, please either use the slack room or email the professor today so we can have everything settled by tomorrow to submit on time.

**Comment by Cantal0p3** [comment]
I am taking out the code- get_popular_ice_cream() from the master branch and creating a new branch for that, so that the method is not there at all in the master. This was only an enhancement to demo how to use query parameter.

**Comment by Cantal0p3** [comment]
I have removed the code for get_popular_ice_cream(). Since it was only an enhancement I don't think it will impact our project goals.
Right now the methods in the file icecream.py are -
1. LIST ALL resourceS
2. RETRIEVE A resource
3. ADD A NEW Ice cream flavor 
4. UPDATE AN EXISTING resource
5. DELETE A resource
6. QUERY Resources by some attribute of the Resource - Type: Melted/Frozen
7. PERFORM some Action on the Resource - UPDATE a resource status
8. utility functions

**Comment by rofrano** [comment]
@Cantal0p3 & @skyline220 Just to clarify. You cannot have two Python functions that have the same URL signature because Flask will not know which one to send it call. You do not have to physically put all of the functionality under one method. In fact you should write separate functions but then make one Flask method that calls the other functions as appropriate.

As it stands now, your Query method does not work because it has the same URL signature as the Retrieve method:

**RETRIEVE A resource:**
```
@app.route('/ice-creams/<id>', methods=['GET'])
def get_an_ice_cream(id):
```
**QUERY Resources by some attribute of the Resource - Type: Melted/Frozen**
```
@app.route('/ice-creams/<id>', methods=['GET'])
def list_resources_by_type():
```
This is because these two URL signatures are the same:
```
@app.route('/ice-creams/<id>', methods=['GET'])
@app.route('/ice-creams/<id>', methods=['GET'])
```
So I could not get the Query to work. :(
